// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qpcqkhebkzhqbomlzwye.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFwY3FraGVia3pocWJvbWx6d3llIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3OTYzMzksImV4cCI6MjA3MTM3MjMzOX0.7G7ZfqM7U0DmfOmOK9H2mTiC2L--VIjCDpgTz64hPa0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});